# Generated by Django 5.0.6 on 2024-07-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='password',
        ),
    ]
